### ISSUE TITLE
Update USI links

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/ms2ldaviz#165]
Update USI links. Details:

mzspec:MOTIFDB:motif:171163 -> mzspec:MOTIFDB::accession:171163
mzspec:MS2LDATASK-38:document:43062 -> mzspec:MS2LDA:TASK-38:accession:43062

**Comment by joewandy** [comment]
Any idea what's this @justinjjvanderhooft

**Comment by sdrogers** [comment]
I think it's a change in format of the USI links, and ours might be out of date. If you click one, and it works, it probably means that I already fixed this and didn't close (sorry)

**Comment by justinjjvanderhooft** [comment]
Thanks Simon for the explanation! 😎

**Comment by joewandy** [comment]
Seems like it's still working
