### ISSUE TITLE
Summary page is slooooww

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/ms2ldaviz#172]
1. It's slow because of the 4 datatables, which load all the data when the page shows. We should change it so the table only loads what it needs. This probably needs quite a lot of work (changing views, templates, js etc).
2. An interim solution is to simply cache the two big features and document tables, since they shouldn't change anymore once the data is created.

**Comment by justinjjvanderhooft** [comment]
Let's try the caching first....

**Comment by joewandy** [comment]
view_parents page is also slow and can be sped up.

![image](https://user-images.githubusercontent.com/2523391/127521667-0d8b722a-8a34-421e-b633-42f727c5417b.png)

**Comment by joewandy** [comment]
FIxed in commits https://github.com/glasgowcompbio/ms2ldaviz/commit/bd18d193cc8ee8932cd5dacdbf7c4a3ce9db30a6, https://github.com/glasgowcompbio/ms2ldaviz/commit/89776988259516887d000ea4eda615bf96160553, and https://github.com/glasgowcompbio/ms2ldaviz/commit/f670f3b62b48945592bfd36c9c1deac2d076ce14. These pages now load much much faster.
