### ISSUE TITLE
Don't display Magma annotation if it isn't there

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/ms2ldaviz#175]
See the screenshot below from the show motif page. Instead of displaying 'None' when there's no magma annotation found, I think it's better not to display anything at all?

![image](https://user-images.githubusercontent.com/2523391/127999090-39b42c7e-7727-44a1-bf5b-c72c9058e963.png)

**Comment by justinjjvanderhooft** [comment]
Agreed!

**Comment by joewandy** [comment]
Done, but noticed some other issue https://github.com/glasgowcompbio/ms2ldaviz/issues/179
