### ISSUE TITLE
Check MGF parser metadata fields and how we handle them

### ISSUE THREAD

**Issue by justinjjvanderhooft** [glasgowcompbio/ms2ldaviz#92]
Since MSP and MGF formats are a bit unspecified - would the following be an idea: 
First upload the MGF file into the system and then let the user pick out which of the metadata fields are important. For example, in the MGF experiment of the diterpenoids, the RTs are mentioned in the MGF file (RTinseconds) but not displayed in the MS2LDA model. We could store the metadata and let the user select and link the appropiate metadata fields to the parameters that we use (i.e., link RTinseconds to RT).

**Comment by joewandy** [comment]
Too much work.

**Comment by justinjjvanderhooft** [comment]
Simon (and me) is working on this! 🙂
